#!/bin/bash
python3 ../main.py --dir /data2/hhjung/SpatialNorm/P1/batch/First --Mode 0 --Method P1 --gpu 0 --layer 2 --norm-type batch 1> /dev/null &
python3 ../main.py --dir /data2/hhjung/SpatialNorm/P1/batch/Last --Mode 1 --Method P1 --gpu 1 --layer 2 --norm-type batch 1> /dev/null &
python3 ../main.py --dir /data2/hhjung/SpatialNorm/P1/batch/All --Mode 2 --Method P1 --gpu 2 --layer 2 --norm-type batch 1> /dev/null &
python3 ../main.py --dir /data2/hhjung/SpatialNorm/P2/batch/First --Mode 0 --Method P2 --gpu 3 --layer 2 --norm-type batch 1> /dev/null &
python3 ../main.py --dir /data2/hhjung/SpatialNorm/P2/batch/Last --Mode 1 --Method P2 --gpu 4 --layer 2 --norm-type batch 1> /dev/null &
python3 ../main.py --dir /data2/hhjung/SpatialNorm/P2/batch/All --Mode 2 --Method P2 --gpu 5 --layer 2 --norm-type batch 1> /dev/null &
python3 ../main.py --dir /data2/hhjung/SpatialNorm/P1/instance/All --Mode 2 --Method P1 --gpu 6 --layer 2 --norm-type instance 1> /dev/null &
python3 ../main.py --dir /data2/hhjung/SpatialNorm/P2/instance/All --Mode 2 --Method P2 --gpu 7 --layer 2 --norm-type instance 1> /dev/null
