#!/bin/bash
python3 ../main.py --dir /data2/hhjung/Norm4/P2/Last/group2/batch16 --Mode 1 -b 16 --Method P2 --group 2 --gpu 4 --layer 2 1> /dev/null && 
python3 ../main.py --dir /data2/hhjung/Norm4/P2/Last/group2/batch32 --Mode 1 -b 32 --Method P2 --group 2 --gpu 4 --layer 2 1> /dev/null && 
python3 ../main.py --dir /data2/hhjung/Norm4/P2/Last/group2/batch64 --Mode 1 -b 64 --Method P2 --group 2 --gpu 4 --layer 2 1> /dev/null && 
python3 ../main.py --dir /data2/hhjung/Norm4/P2/Last/group2/batch128 --Mode 1 -b 128 --Method P2 --group 2 --gpu 4 --layer 2 1> /dev/null && 
python3 ../main.py --dir /data2/hhjung/Norm4/P2/Last/group4/batch16 --Mode 1 -b 16 --Method P2 --group 4 --gpu 4 --layer 2 1> /dev/null &&
python3 ../main.py --dir /data2/hhjung/Norm4/P2/Last/group4/batch32 --Mode 1 -b 32 --Method P2 --group 4 --gpu 4 --layer 2 1> /dev/null && 
python3 ../main.py --dir /data2/hhjung/Norm4/P2/Last/group4/batch64 --Mode 1 -b 64 --Method P2 --group 4 --gpu 4 --layer 2 1> /dev/null && 
python3 ../main.py --dir /data2/hhjung/Norm4/P2/Last/group4/batch128 --Mode 1 -b 128 --Method P2 --group 4 --gpu 4 --layer 2 1> /dev/null && 
python3 ../main.py --dir /data2/hhjung/Norm4/P2/Last/group8/batch16 --Mode 1 -b 16 --Method P2 --group 8 --gpu 4 --layer 2 1> /dev/null &&
python3 ../main.py --dir /data2/hhjung/Norm4/P2/Last/group8/batch32 --Mode 1 -b 32 --Method P2 --group 8 --gpu 4 --layer 2 1> /dev/null && 
python3 ../main.py --dir /data2/hhjung/Norm4/P2/Last/group8/batch64 --Mode 1 -b 64 --Method P2 --group 8 --gpu 4 --layer 2 1> /dev/null && 
python3 ../main.py --dir /data2/hhjung/Norm4/P2/Last/group8/batch128 --Mode 1 -b 128 --Method P2 --group 8 --gpu 4 --layer 2 1> /dev/null && 
python3 ../main.py --dir /data2/hhjung/Norm4/P2/Last/group16/batch16 --Mode 1 -b 16 --Method P2 --group 16 --gpu 4 --layer 2 1> /dev/null &&
python3 ../main.py --dir /data2/hhjung/Norm4/P2/Last/group16/batch32 --Mode 1 -b 32 --Method P2 --group 16 --gpu 4 --layer 2 1> /dev/null && 
python3 ../main.py --dir /data2/hhjung/Norm4/P2/Last/group16/batch64 --Mode 1 -b 64 --Method P2 --group 16 --gpu 4 --layer 2 1> /dev/null && 
python3 ../main.py --dir /data2/hhjung/Norm4/P2/Last/group16/batch128 --Mode 1 -b 128 --Method P2 --group 16 --gpu 4 --layer 2 1> /dev/null
