#!/bin/bash
python3 main.py --dir /data2/hhjung/Normalization/gn/group8/batch16 -b 16 --Method GN --group 8 --gpu 0 --layer 2 1> /dev/null && 
python3 main.py --dir /data2/hhjung/Normalization/gn/group8/batch32 -b 32 --Method GN --group 8 --gpu 0 --layer 2 1> /dev/null && 
python3 main.py --dir /data2/hhjung/Normalization/gn/group8/batch64 -b 64 --Method GN --group 8 --gpu 0 --layer 2 1> /dev/null && 
python3 main.py --dir /data2/hhjung/Normalization/gn/group8/batch128 -b 128 --Method GN --group 8 --gpu 0 --layer 2 1> /dev/null
