#!/bin/bash
python3 ../main.py --dir /data2/hhjung/Norm2/GN/First/group4/batch16 -b 16 --Method GN --group 4 --gpu 5 --layer 2 1> /dev/null &&
python3 ../main.py --dir /data2/hhjung/Norm2/GN/First/group4/batch32 -b 32 --Method GN --group 4 --gpu 5 --layer 2 1> /dev/null && 
python3 ../main.py --dir /data2/hhjung/Norm2/GN/First/group4/batch64 -b 64 --Method GN --group 4 --gpu 5 --layer 2 1> /dev/null && 
python3 ../main.py --dir /data2/hhjung/Norm2/GN/First/group4/batch128 -b 128 --Method GN --group 4 --gpu 5 --layer 2 1> /dev/null
