#!/bin/bash
python3 ../main.py --dir /data2/hhjung/Norm2/GN/First/group16/batch16 -b 16 --Method GN --group 16 --gpu 7 --layer 2 1> /dev/null &&
python3 ../main.py --dir /data2/hhjung/Norm2/GN/First/group16/batch32 -b 32 --Method GN --group 16 --gpu 7 --layer 2 1> /dev/null && 
python3 ../main.py --dir /data2/hhjung/Norm2/GN/First/group16/batch64 -b 64 --Method GN --group 16 --gpu 7 --layer 2 1> /dev/null && 
python3 ../main.py --dir /data2/hhjung/Norm2/GN/First/group16/batch128 -b 128 --Method GN --group 16 --gpu 7 --layer 2 1> /dev/null
