#!/bin/bash
python3 ../main.py --dir /data2/hhjung/Norm2/P1/group8/batch32 -b 32 --Method P1 --group 8 --gpu 2 --layer 2 1> /dev/null && 
python3 ../main.py --dir /data2/hhjung/Norm2/P1/group8/batch64 -b 64 --Method P1 --group 8 --gpu 2 --layer 2 1> /dev/null && 
python3 ../main.py --dir /data2/hhjung/Norm2/P1/group8/batch128 -b 128 --Method P1 --group 8 --gpu 2 --layer 2 1> /dev/null
